apiVersion: apps/v1
kind: Deployment
metadata:
  name: threat-api
  labels:
    app: threat-api
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: threat-api
      tier: backend

  template:
    metadata:
      labels:
        app: threat-api
        tier: backend
    spec:
      containers:
      - name: threat-api-pod
        image: yakov234/threat-api:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8000

        env:
        - name: MONGO_HOST
          value: "mongo-0.mongo"
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_USERNAME
          value: "admin"
        - name: MONGO_PASSWORD
          value: "secretpass"
        - name: MONGO_DB
          value: "threat_db"
